version: "3.7"

services:
  paiba-server:
    container_name: "paiba-server"
    build:
      context: server
      dockerfile: Dockerfile
    # environment:
    # NODE_ENV: production
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 3000:3000
  paiba-client:
    container_name: "paiba-client"
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 8080:8080
